### ISSUE TITLE
<Spreadsheet /> should display focused cell in format rowIndex — columnIndex if cell is focused:

### ISSUE THREAD

**Issue by Enoch2k2** [learn-co-curriculum/react-actions-lab#6]
So i ran into this issue with the hyphens. The standard hyphen is shorter then the one declared in the test. So it won't pass it due to that. Going to PR a fix for this.

Error:

  1) <Spreadsheet /> should display focused cell in format rowIndex — columnIndex if cell is focused:
     Error: Expected '1 - 2' to be '1 — 2'
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toBe (node_modules/expect/lib/Expectation.js:66:28)
      at Context.<anonymous> (test/Spreadsheet-test.js:127:58)

**Comment by aturkewi** [comment]
Closed by PR #7
