### ISSUE TITLE
404 on "actions" link

### ISSUE THREAD

**Issue by pajamaw** [learn-co-curriculum/react-actions-lab#8]
on line 15 of the readme the actions link is an incorrect path

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
